### ISSUE TITLE
--<raw article>-- Regex messes up with phrases ending in a Colon " : "

### ISSUE THREAD

**Issue by kittleapps** [ThePsionic/WikiaLinker#20]
While leaving messages such as:

>Test:
>--Special:WikiActivity--

in the message will give output similar to:

> http://runescape.wikia.com/wiki/Test:_Special:WikiActivity

Messages such as:

>:
>--Special:WikiActivity--

Will give output as:

> http://runescape.wikia.com/wiki/:_Special:WikiActivity

\- Sudo Bash

**Comment by ThePsionic** [comment]
Fixed in https://github.com/ThePsionic/WikiaLinker/commit/f8ddc70f6ccb556e9fe029efcf8196e6c011839e
